# Generated by Django 6.0.7 on 2026-07-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_facebook',
            field=models.CharField(blank=True, help_text='Facebook profile URL or name, used as a backup contact method.', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='down_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount required upfront to secure the booking (e.g. 50% of total cost).', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Refundable deposit collected at pickup, returned on safe return of the gear.', max_digits=10),
        ),
    ]
