# Generated by Django 6.0.7 on 2026-07-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_booking_contact_facebook_booking_down_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addons',
            field=models.ManyToManyField(blank=True, help_text='Optional add-on accessories included with this booking.', related_name='addon_bookings', to='rentals.equipment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('gotyme', 'GoTyme Bank'), ('maribank', 'Maribank'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('gotyme', 'GoTyme Bank'), ('maribank', 'Maribank'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='cash', max_length=20),
        ),
    ]
