# Generated by Django 6.0.7 on 2026-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_contact_number_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.CharField(blank=True, help_text='Facebook profile URL, used as a backup contact method.', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_id',
            field=models.ImageField(blank=True, help_text='Photo of a government-issued ID, used to verify identity for rentals.', null=True, upload_to='user_ids/'),
        ),
    ]
